In [ ]:
# 📌 서로 다른 두 개의 데이터 프레임 연결하기

In [3]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "customer_id": [1, 2, 3],
    "customer_name": ["Robert", "Peter", "Dave"]
}, columns=["id", "customer_id", "customer_name"])

# 3개의 컬럼(=시리즈)가 완성된 거고 그 시리즈들의 키는 id, customer_id, name인 것!
df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [6]:
df2 = pd.DataFrame({
    "id": [1, 2, 4],
    "order_id": [100, 200, 300],
    "order_date": ["2025-01-21", "2025-02-03", "2025-09-01"]
}, columns=["id", "order_id", "order_date"])

df2

   id  order_id  order_date
0   1       100  2025-01-21
1   2       200  2025-02-03
2   4       300  2025-09-01

#### 🚩 **서로 다른 데이터 프레임을 하나로 합치는 방법**
1) concat() : 서로 다른 데이터 프레임을 단순 연결만 시킴(무식) (*교차되는 특정 인덱스를 고려X) -> 좌우, 상하로도 합칠 수 있음 = 유연함 (디폴트는 상하) *반갑슨~
2) merge() : 특정 인덱스를 기준으로 합침 (concat보다도 JOIN에 더 가까움)

In [7]:
pd.concat([df1, df2])
# 진짜 그냥... 위아래로 합침...;; df1에는 order_id,order_date 컬럼 자체가 없기 때문에 다 NaN임

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0          Dave       NaN         NaN
0   1          NaN           NaN     100.0  2025-01-21
1   2          NaN           NaN     200.0  2025-02-03
2   4          NaN           NaN     300.0  2025-09-01